### ISSUE TITLE
AttributeError: type object 'MySpMM' has no attribute 'apply'

### ISSUE THREAD

**Issue by AmazingSean** [muhanzhang/pytorch_DGCNN#11]
Hi!
I got this error when running with python 2.7.15 under gpu mode

```
Traceback (most recent call last):
  File "main.py", line 187, in <module>
    avg_loss = loop_dataset(train_graphs, classifier, train_idxes, optimizer=op\
timizer)
  File "main.py", line 131, in loop_dataset
    logits, loss, acc = classifier(batch_graph)
  File "/home/wyw10804/anaconda2/envs/env_DGCNN/lib/python2.7/site-packages/tor\
ch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "main.py", line 107, in forward
    embed = self.s2v(batch_graph, node_feat, None)
  File "/home/wyw10804/anaconda2/envs/env_DGCNN/lib/python2.7/site-packages/tor\
ch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wyw10804/ssl-graph-classification/benchmarks/pytorch_DGCNN-master\
/DGCNN_embedding.py", line 71, in forward
    h = self.sortpooling_embedding(node_feat, edge_feat, n2n_sp, e2n_sp, subg_s\
p, graph_sizes, node_degs)
  File "/home/wyw10804/ssl-graph-classification/benchmarks/pytorch_DGCNN-master\
/DGCNN_embedding.py", line 87, in sortpooling_embedding
    n2npool = gnn_spmm(n2n_sp, cur_message_layer) + cur_message_layer  # Y = (A\
 + I) * X
  File "/home/wyw10804/ssl-graph-classification/benchmarks/pytorch_DGCNN-master\
/pytorch_structure2vec-master/s2v_lib/pytorch_util.py", line 70, in gnn_spmm
    return MySpMM.apply(sp_mat, dense_mat)
AttributeError: type object 'MySpMM' has no attribute 'apply'
```
Can you help me with this issue? Thanks!

**Comment by muhanzhang** [comment]
Hi, sorry for the late reply. Actually I have had the same issue as yours when installing Hanjun Dai's pytorch_structure2vec, check here https://github.com/Hanjun-Dai/pytorch_structure2vec/issues/6

So probably reinstalling pytorch again? Let me know if it solves your issue.

**Comment by AmazingSean** [comment]
> Hi, sorry for the late reply. Actually I have had the same issue as yours when installing Hanjun Dai's pytorch_structure2vec, check here [Hanjun-Dai/pytorch_structure2vec#6](https://github.com/Hanjun-Dai/pytorch_structure2vec/issues/6)
> 
> So probably reinstalling pytorch again? Let me know if it solves your issue.

It works out perfectly! Thank you muhan!
