### ISSUE TITLE
An error about SEAL-master python code Main.py

### ISSUE THREAD

**Issue by Toheng633** [muhanzhang/pytorch_DGCNN#36]
Hi Muhan, I have an error when I run the code Main.py on windows,
Can you give me some advice?
Thank you so much~

Traceback (most recent call last):
  File "E:/iSS/SEAL-master/Python/Main.py", line 12, in <module>
    from main import *
  File "E:\iSS\SEAL-master\Python/pytorch_DGCNN\main.py", line 14, in <module>
    from DGCNN_embedding import DGCNN
  File "E:\iSS\SEAL-master\Python/pytorch_DGCNN\DGCNN_embedding.py", line 17, in <module>
    from gnn_lib import GNNLIB
  File "E:\iSS\SEAL-master\Python\pytorch_DGCNN/lib\gnn_lib.py", line 87, in <module>
    GNNLIB = _gnn_lib(sys.argv)
  File "E:\iSS\SEAL-master\Python\pytorch_DGCNN/lib\gnn_lib.py", line 12, in __init__
    self.lib = ctypes.CDLL('%s/build/dll/libgnn.so' % dir_path)
  File "E:\Python\Anaconda3\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by muhanzhang** [comment]
Hi! Pytorch_DGCNN does not support windows well. One solution is to use remote linux servers; the other is to install ubuntu sub-system in windows 10. See #27.
